version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 50
    target-branch: "2.1.x"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.eclipse.jetty:*"
        versions: [ ">=11.0.0" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
