name: Release Drafter

on:
  push:
    branches:
      - 1.0.x
      - 2.0.x

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.20.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
